version: "3.9"

services:
  pneumonia-app:
    build: .
    container_name: pneumonia-detection-ai

    ports:
      - "8501:8501"

    volumes:
      - .:/app

    restart: unless-stopped

    command: streamlit run app.py --server.address=0.0.0.0